package com.github.stephenwanjala.brecipes.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF003507)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005611)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF173215)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF335030)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003139)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00515D)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7FBF0)
val onBackgroundLightHighContrast = Color(0xFF181D17)
val surfaceLightHighContrast = Color(0xFFF7FBF0)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE6D5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF262E24)
val outlineVariantLightHighContrast = Color(0xFF434C40)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D322B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF8AD983)
val surfaceDimLightHighContrast = Color(0xFFB6BAB1)
val surfaceBrightLightHighContrast = Color(0xFFF7FBF0)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF2E8)
val surfaceContainerLightHighContrast = Color(0xFFE0E4DA)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D6CC)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C8BE)

val primaryDarkHighContrast = Color(0xFFC5FFBB)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF86D57F)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F01)
val secondaryDarkHighContrast = Color(0xFFD7FACE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFAACCA3)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F01)
val tertiaryDarkHighContrast = Color(0xFFD3F6FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF4FD3EC)
val onTertiaryContainerDarkHighContrast = Color(0xFF000D11)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF10150F)
val onBackgroundDarkHighContrast = Color(0xFFE0E4DA)
val surfaceDarkHighContrast = Color(0xFF10150F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF40493D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE9F3E2)
val outlineVariantDarkHighContrast = Color(0xFFBCC6B6)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE0E4DA)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005411)
val surfaceDimDarkHighContrast = Color(0xFF10150F)
val surfaceBrightDarkHighContrast = Color(0xFF4D514A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C211B)
val surfaceContainerDarkHighContrast = Color(0xFF2D322B)
val surfaceContainerHighDarkHighContrast = Color(0xFF383D36)
val surfaceContainerHighestDarkHighContrast = Color(0xFF434841)







